openapi: 3.0.0
info:
  title: expenses-dashboard-api
  description: 支出管理アプリ用API
  version: 0.1.0
servers:
  - url: http://{host}:{port}/api
    description: for development
    variables:
      host:
        default: localhost
      port:
        default: "5000"

tags:
  - name: Receipts
    description: レシートの情報にアクセスする
  - name: Shops
    description: 店の情報にアクセスする
  - name: Taxes
    description: 消費税の情報にアクセスする

paths:
  /receipts:
    get:
      tags:
        - Receipts
      summary: レシート一覧を取得
      description: 条件を指定してレシート一覧を取得する
      parameters:
        - in: query
          name: since
          description: 検索対象とする日付の最小値
          schema:
            $ref: "#/components/schemas/date"
        - in: query
          name: until
          description: 検索対象とする日付の最大値
          schema:
            $ref: "#/components/schemas/date"
        - in: query
          name: shop_id_list
          description: 検索対象とする店IDのリスト
          schema:
            type: array
            items:
              $ref: "#/components/schemas/shop_id"
      responses:
        "200":
          $ref: "#/components/responses/ReceiptList"
    post:
      tags:
        - Receipts
      summary: 新しいレシートを登録
      requestBody:
        $ref: "#/components/requestBodies/NewOrUpdatedReceipt"
      responses:
        "200":
          $ref: "#/components/responses/ReceiptDetail"
  /receipts/{receipt_id}:
    get:
      tags:
        - Receipts
      summary: レシートIDを指定して詳細を取得
      parameters:
        - in: path
          name: receipt_id
          required: true
          schema:
            $ref: "#/components/schemas/receipt_id"
      responses:
        "200":
          $ref: "#/components/responses/ReceiptDetail"
    patch:
      tags:
        - Receipts
      summary: レシートIDを指定して更新
      parameters:
        - in: path
          name: receipt_id
          required: true
          schema:
            $ref: "#/components/schemas/receipt_id"
      requestBody:
        $ref: "#/components/requestBodies/NewOrUpdatedReceipt"
      responses:
        "200":
          $ref: "#/components/responses/ReceiptDetail"
    delete:
      tags:
        - Receipts
      summary: レシートIDを指定して削除
      parameters:
        - in: path
          name: receipt_id
          required: true
          schema:
            $ref: "#/components/schemas/receipt_id"
      responses:
        "200":
          description: The resource was deleted successefully.
  /shops:
    get:
      tags:
        - Shops
      summary: 店一覧を取得
      responses:
        "200":
          $ref: "#/components/responses/ShopList"
    post:
      tags:
        - Shops
      summary: 新しい店名を登録
      requestBody:
        $ref: "#/components/requestBodies/NewOrUpdatedShop"
      responses:
        "200":
          $ref: "#/components/responses/NewOrUpdatedShop"
  /shops/{shop_id}:
    patch:
      tags:
      - Shops
      parameters:
        - in: path
          name: shop_id
          required: true
          schema:
            $ref: "#/components/schemas/shop_id"

      summary: 店名を更新
      requestBody:
        $ref: "#/components/requestBodies/NewOrUpdatedShop"
      responses:
        "200":
          $ref: "#/components/responses/NewOrUpdatedShop"

  /taxes:
    get:
      tags:
        - Taxes
      summary: 消費税の種類一覧を取得
      responses:
        "200":
          $ref: "#/components/responses/TaxList"
    post:
      tags:
        - Taxes
      summary: 新しい消費税率を登録
      requestBody:
        $ref: "#/components/requestBodies/NewOrUpdatedTaxRate"
      responses:
        "200":
          $ref: "#/components/responses/NewOrUpdatedTax"

  /taxes/{tax_id}:
    put:
      tags:
        - Taxes
      parameters:
        - in: path
          name: tax_id
          required: true
          schema:
            $ref: "#/components/schemas/tax_id"
      summary: 税IDを指定して更新
      requestBody:
        $ref: "#/components/requestBodies/NewOrUpdatedTaxRate"
      responses:
        "200":
          $ref: "#/components/responses/NewOrUpdatedTax"
    # delete:
    #   tags:
    #     - Taxes
    #   parameters:
    #     - in: path
    #       name: tax_id
    #       required: true
    #       schema:
    #         $ref: "#/components/schemas/tax_id"
    #   summary: 税IDを指定して削除
    #   responses:
    #     "200":
    #       description: The resource was deleted successefully.

components:
  schemas:
    shop_id:
      type: integer
      description: 店ID
    shop_name:
      type: string
      description: 店名
    date:
      type: string
      description: 時刻なし日付
    timestamp:
      type: string
      description: 時刻あり日付
    price:
      type: integer
      description: 金額
    receipt_id:
      type: integer
      description: レシートID
    product_id:
      type: integer
      description: 購入品ID
    product_name:
      type: string
      description: 商品名
    tax_id:
      type: integer
      description: 消費税ID
    tax_rate:
      type: integer
      description: 消費税率
    tax_item:
      type: object
      description: 消費税IDと消費税率のペア
      properties:
        tax_id:
          $ref: "#/components/schemas/tax_id"
        tax_rate:
          $ref: "#/components/schemas/tax_rate"
    tax_list:
      type: array
      items:
        $ref: "#/components/schemas/tax_item"
    shop_item:
      type: object
      description: 店情報
      properties:
        shop_id:
          $ref: "#/components/schemas/shop_id"
        shop_name:
          $ref: "#/components/schemas/shop_name"
        modified_at:
          $ref: "#/components/schemas/timestamp"
        created_at:
          $ref: "#/components/schemas/timestamp"
    shop_summary:
      type: object
      description: 簡易的な店情報
      properties:
        shop_id:
          $ref: "#/components/schemas/shop_id"
        shop_name:
          $ref: "#/components/schemas/shop_name"
    shop_list:
      type: array
      description: 店一覧
      items:
        $ref: "#/components/schemas/shop_item"
    product_item:
      type: object
      description: 商品リストの1要素
      properties:
        product_id:
          $ref: "#/components/schemas/product_id"
        product_name:
          $ref: "#/components/schemas/product_name"
        price_wo_tax:
          $ref: "#/components/schemas/price"
        tax_id:
          $ref: "#/components/schemas/tax_id"
    product_list:
      type: array
      items:
        $ref: "#/components/schemas/product_item"
    receipt_detail:
      type: object
      description: レシート詳細
      properties:
        receipt_id:
          $ref: "#/components/schemas/receipt_id"
        shop_id:
          $ref: "#/components/schemas/shop_id"
        shop_name:
          $ref: "#/components/schemas/shop_name"
        purchase_date:
          $ref: "#/components/schemas/date"
        discount_price:
          $ref: "#/components/schemas/price"
        total_price_including_tax:
          $ref: "#/components/schemas/price"
        modified_at:
          $ref: "#/components/schemas/date"
        created_at:
          $ref: "#/components/schemas/date"

        product_list:
          $ref: "#/components/schemas/product_list"
    receipt_item:
      type: object
      description: レシート一覧の1要素
      properties:
        receipt_id:
          $ref: "#/components/schemas/receipt_id"
        shop_id:
          $ref: "#/components/schemas/shop_id"
        shop_name:
          $ref: "#/components/schemas/shop_name"
        purchase_date:
          $ref: "#/components/schemas/date"
        discount_price:
          $ref: "#/components/schemas/price"
        total_price_includes_tax:
          $ref: "#/components/schemas/price"
        modified_at:
          $ref: "#/components/schemas/timestamp"
        created_at:
          $ref: "#/components/schemas/timestamp"
    receipt_list:
      type: array
      description: レシート一覧
      items:
        $ref: "#/components/schemas/receipt_item"
  responses:
    ReceiptList:
      description: 条件を満たすレシートの一覧
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/receipt_list"
    NewOrUpdatedShop:
      description: 新規登録もしくは更新された店情報
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/shop_item"
    ShopList:
      description: 店の一覧
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/shop_list"
    TaxList:
      description: 消費税の種類一覧
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/tax_list"
    NewOrUpdatedTax:
      description: 新規登録もしくは更新された消費税
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/tax_item"
    ReceiptDetail:
      description: レシート詳細
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/receipt_detail"
  requestBodies:
    NewOrUpdatedShop:
      required: true
      description: 新しい店名
      content:
        application/json:
          schema:
            type: object
            properties:
              shop_name:
                $ref: "#/components/schemas/shop_name"
    NewOrUpdatedTaxRate:
      required: true
      description: 新しいもしくは更新後の消費税率
      content:
        application/json:
          schema:
            type: object
            properties:
              tax_rate:
                $ref: "#/components/schemas/tax_rate"
    NewOrUpdatedReceipt:
      required: true
      description: 新規登録されたレシート
      content:
        application/json:
          schema:
            type: object
            properties:
              shop_id:
                $ref: "#/components/schemas/shop_id"
              purchase_date:
                $ref: "#/components/schemas/date"
              discount_price:
                $ref: "#/components/schemas/price"
              total_price_includes_tax:
                $ref: "#/components/schemas/price"
              product_list:
                $ref: "#/components/schemas/product_list"